// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/forgot-password": {
    params: {};
  };
  "/update-password": {
    params: {};
  };
  "/auth/confirm": {
    params: {};
  };
  "/auth/verify": {
    params: {};
  };
  "/auth/error": {
    params: {};
  };
  "/auth/oauth": {
    params: {};
  };
  "/protected": {
    params: {};
  };
  "/counter": {
    params: {};
  };
  "/sign-up": {
    params: {};
  };
  "/logout": {
    params: {};
  };
  "/login": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/forgot-password" | "/update-password" | "/auth/confirm" | "/auth/verify" | "/auth/error" | "/auth/oauth" | "/protected" | "/counter" | "/sign-up" | "/logout" | "/login";
  };
  "routes/forgot-password.tsx": {
    id: "routes/forgot-password";
    page: "/forgot-password";
  };
  "routes/update-password.tsx": {
    id: "routes/update-password";
    page: "/update-password";
  };
  "routes/auth.confirm.tsx": {
    id: "routes/auth.confirm";
    page: "/auth/confirm";
  };
  "routes/auth.verify.tsx": {
    id: "routes/auth.verify";
    page: "/auth/verify";
  };
  "routes/auth.error.tsx": {
    id: "routes/auth.error";
    page: "/auth/error";
  };
  "routes/auth.oauth.tsx": {
    id: "routes/auth.oauth";
    page: "/auth/oauth";
  };
  "routes/protected.tsx": {
    id: "routes/protected";
    page: "/protected";
  };
  "routes/counter.tsx": {
    id: "routes/counter";
    page: "/counter";
  };
  "routes/sign-up.tsx": {
    id: "routes/sign-up";
    page: "/sign-up";
  };
  "routes/_index.tsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/logout.tsx": {
    id: "routes/logout";
    page: "/logout";
  };
  "routes/login.tsx": {
    id: "routes/login";
    page: "/login";
  };
};