// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/counter": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/counter";
  };
  "./routes/index.tsx": {
    id: "routes/index";
    page: "/";
  };
  "./routes/counter.tsx": {
    id: "routes/counter";
    page: "/counter";
  };
};