export const EnvKeys = {
  /**
   * DB
   */
  DATABASE_URL: 'DATABASE_URL',
  SUPABASE_URL: 'SUPABASE_URL',
  SUPABASE_ANON_KEY: 'SUPABASE_ANON_KEY',
  SUPABASE_SERVICE_ROLE_KEY: 'SUPABASE_SERVICE_ROLE_KEY',
  /**
   * CORS
   */
  CORS_ENABLE_ORIGIN_LOCAL: 'CORS_ENABLE_ORIGIN_LOCAL',
  CORS_ENABLE_ORIGIN_ROOT: 'CORS_ENABLE_ORIGIN_ROOT',
  CORS_ENABLE_ORIGIN_APP: 'CORS_ENABLE_ORIGIN_APP',
} as const;

export type EnvKey = keyof typeof EnvKeys;
